export const FETCH_ALL_SHOES_SUCCESS = "FETCH_ALL_SHOES_SUCCESS";
export const FETCH_MEN_SHOES_SUCCESS = "FETCH_MEN_SHOES_SUCCESS";
export const FETCH_WOMEN_SHOES_SUCCESS = "FETCH_WOMEN_SHOES_SUCCESS";
export const FETCH_CHILDREN_SHOES_SUCCESS = "FETCH_CHILDREN_SHOES_SUCCESS";
export const FETCH_ALL_SHOES_FAIL = "FETCH_ALL_SHOES_FAIL";
export const FETCH_MEN_SHOES_FAIL = "FETCH_MEN_SHOES_FAIL";
export const FETCH_WOMEN_SHOES_FAIL = "FETCH_WOMEN_SHOES_FAIL";
export const FETCH_CHILDREN_SHOES_FAIL = "FETCH_CHILDREN_SHOES_FAIL";
export const DATA_ISLOADING = "DATA_ISLOADING";
export const FETCH_BRANDS_SUCCESS = "FETCH_BRANDS_SUCCESS";
export const FETCH_BRANDS_FAIL = "FETCH_BRANDS_FAIL";
export const ADD_FILTER_BRAND = "ADD_FILTER_BRAND";
export const REMOVE_FILTER_BRAND = "REMOVE_FILTER_BRAND";

export const MINMAX__ALLSHOES = "MINMAX__ALLSHOES";
export const MINMAX__MENSHOES = "MINMAX__MENSHOES";
export const MINMAX__WOMENSHOES = "MINMAX__WOMENSHOES";
export const MINMAX__CHILDRENSHOES = "MINMAX__CHILDRENSHOES";

export const FILTER__PRICE__ALLSHOES = "FILTER__PRICE__ALLSHOES";
export const FILTER__PRICE__MENSHOES = "FILTER__PRICE__MENSHOES";
export const FILTER__PRICE__WOMENSHOES = "FILTER__PRICE__WOMENSHOES";
export const FILTER__PRICE__CHILDRENSHOES = "FILTER__PRICE__CHILDRENSHOES";