export const FETCH_SHOES_SUCCESS = "FETCH_SHOES_SUCCESS";
export const FETCH_SHOES_FAIL = "FETCH_SHOES_FAIL";
export const CATEGORY_SHOE_BRANDS = "CATEGORY_SHOE_BRANDS";
export const MINMAX__SHOES = "MINMAX__SHOES";
export const FILTER__PRICE = "FILTER__PRICE";
export const CLEAR__FILTER__PRICE = "CLEAR__FILTER__PRICE";

export const DATA_ISLOADING = "DATA_ISLOADING";
export const ADD_FILTER_BRAND = "ADD_FILTER_BRAND";
export const REMOVE_FILTER_BRAND = "REMOVE_FILTER_BRAND";
export const CLEAR_FILTER_BRANDS = "CLEAR_FILTER_BRANDS";